// Comprehensive exercise database
export const exerciseDatabase = {
  strength: {
    "full-body": [
      {
        name: "Barbell Squat",
        sets: 4,
        reps: "6-8",
        rest: "2-3 min",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Bench Press",
        sets: 4,
        reps: "6-8",
        rest: "2-3 min",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Deadlift",
        sets: 3,
        reps: "5-6",
        rest: "3 min",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Pull-ups",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Overhead Press",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Barbell Rows",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Pull",
      },
      { name: "Dips", sets: 3, reps: "8-12", rest: "2 min", equipment: ["bodyweight"], muscleGroup: "Upper Body Push" },
      {
        name: "Lunges",
        sets: 3,
        reps: "10-12 per leg",
        rest: "2 min",
        equipment: ["bodyweight", "dumbbells"],
        muscleGroup: "Lower Body Push",
      },
      { name: "Face Pulls", sets: 3, reps: "12-15", rest: "1-2 min", equipment: ["cables"], muscleGroup: "Shoulders" },
      { name: "Plank", sets: 3, duration: "30-60 sec", rest: "1 min", equipment: ["bodyweight"], muscleGroup: "Core" },
    ],
    "upper-body": [
      {
        name: "Bench Press",
        sets: 4,
        reps: "6-8",
        rest: "2-3 min",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Bent Over Rows",
        sets: 4,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Overhead Press",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Pull-ups",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Tricep Dips",
        sets: 3,
        reps: "10-12",
        rest: "1-2 min",
        equipment: ["bodyweight", "machine"],
        muscleGroup: "Arms",
      },
      {
        name: "Incline Dumbbell Press",
        sets: 3,
        reps: "8-12",
        rest: "2 min",
        equipment: ["dumbbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Lat Pulldown",
        sets: 3,
        reps: "10-12",
        rest: "2 min",
        equipment: ["machine", "cables"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Lateral Raises",
        sets: 3,
        reps: "12-15",
        rest: "1-2 min",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Bicep Curls",
        sets: 3,
        reps: "10-12",
        rest: "1-2 min",
        equipment: ["dumbbells", "barbells"],
        muscleGroup: "Arms",
      },
      { name: "Tricep Pushdowns", sets: 3, reps: "10-12", rest: "1-2 min", equipment: ["cables"], muscleGroup: "Arms" },
    ],
    "lower-body": [
      {
        name: "Barbell Squat",
        sets: 4,
        reps: "6-8",
        rest: "2-3 min",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Deadlift",
        sets: 3,
        reps: "5-6",
        rest: "3 min",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Leg Press",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Romanian Deadlift",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Calf Raises",
        sets: 3,
        reps: "12-15",
        rest: "1 min",
        equipment: ["bodyweight", "machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Leg Extensions",
        sets: 3,
        reps: "10-12",
        rest: "1-2 min",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Leg Curls",
        sets: 3,
        reps: "10-12",
        rest: "1-2 min",
        equipment: ["machine"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Hip Thrusts",
        sets: 3,
        reps: "10-12",
        rest: "2 min",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Bulgarian Split Squats",
        sets: 3,
        reps: "8-10 per leg",
        rest: "2 min",
        equipment: ["dumbbells", "bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Glute-Ham Raises",
        sets: 3,
        reps: "8-12",
        rest: "2 min",
        equipment: ["machine", "bodyweight"],
        muscleGroup: "Lower Body Pull",
      },
    ],
    push: [
      {
        name: "Bench Press",
        sets: 4,
        reps: "6-8",
        rest: "2-3 min",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Overhead Press",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Incline Bench Press",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Upper Body Push",
      },
      { name: "Dips", sets: 3, reps: "8-12", rest: "2 min", equipment: ["bodyweight"], muscleGroup: "Upper Body Push" },
      { name: "Tricep Pushdowns", sets: 3, reps: "10-12", rest: "1-2 min", equipment: ["cables"], muscleGroup: "Arms" },
      {
        name: "Lateral Raises",
        sets: 3,
        reps: "12-15",
        rest: "1-2 min",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Chest Flyes",
        sets: 3,
        reps: "10-12",
        rest: "1-2 min",
        equipment: ["dumbbells", "cables", "machine"],
        muscleGroup: "Upper Body Push",
      },
    ],
    pull: [
      {
        name: "Pull-ups",
        sets: 4,
        reps: "6-10",
        rest: "2 min",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Barbell Rows",
        sets: 4,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Deadlift",
        sets: 3,
        reps: "5-6",
        rest: "3 min",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Lat Pulldown",
        sets: 3,
        reps: "10-12",
        rest: "2 min",
        equipment: ["machine", "cables"],
        muscleGroup: "Upper Body Pull",
      },
      { name: "Face Pulls", sets: 3, reps: "12-15", rest: "1-2 min", equipment: ["cables"], muscleGroup: "Shoulders" },
      {
        name: "Bicep Curls",
        sets: 3,
        reps: "10-12",
        rest: "1-2 min",
        equipment: ["dumbbells", "barbells"],
        muscleGroup: "Arms",
      },
      { name: "Hammer Curls", sets: 3, reps: "10-12", rest: "1-2 min", equipment: ["dumbbells"], muscleGroup: "Arms" },
    ],
    split: [
      {
        name: "Bench Press",
        sets: 4,
        reps: "6-8",
        rest: "2-3 min",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Push",
      },
      { name: "Squat", sets: 4, reps: "6-8", rest: "2-3 min", equipment: ["barbells"], muscleGroup: "Lower Body Push" },
      {
        name: "Pull-ups",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Romanian Deadlift",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells"],
        muscleGroup: 'Lower Body Pull"  sets: 3, reps: "8-10',
        rest: "2 min",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Overhead Press",
        sets: 3,
        reps: "8-10",
        rest: "2 min",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Leg Press",
        sets: 3,
        reps: "10-12",
        rest: "2 min",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Lat Pulldown",
        sets: 3,
        reps: "10-12",
        rest: "2 min",
        equipment: ["machine", "cables"],
        muscleGroup: "Upper Body Pull",
      },
    ],
  },
  cardio: {
    "full-body": [
      { name: "Jump Rope", duration: "5 min", intensity: "Moderate", equipment: ["jump rope"] },
      { name: "Burpees", sets: 3, reps: "15", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Mountain Climbers", sets: 3, reps: "20 per leg", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Jumping Jacks", duration: "3 min", intensity: "High", equipment: ["bodyweight"] },
      { name: "High Knees", duration: "2 min", intensity: "High", equipment: ["bodyweight"] },
      { name: "Kettlebell Swings", sets: 3, reps: "15-20", rest: "45 sec", equipment: ["kettlebells"] },
      { name: "Box Jumps", sets: 3, reps: "12", rest: "45 sec", equipment: ["box"] },
      { name: "Battle Ropes", sets: 3, duration: "30 sec", rest: "30 sec", equipment: ["ropes"] },
      { name: "Rowing Machine", duration: "5 min", intensity: "High", equipment: ["machine"] },
      { name: "Assault Bike", duration: "3 min", intensity: "Very High", equipment: ["machine"] },
    ],
    "upper-body": [
      { name: "Battle Ropes", sets: 3, duration: "30 sec", rest: "30 sec", equipment: ["ropes"] },
      { name: "Push-up Burpees", sets: 3, reps: "10", rest: "45 sec", equipment: ["bodyweight"] },
      { name: "Medicine Ball Slams", sets: 3, reps: "15", rest: "30 sec", equipment: ["medicine ball"] },
      { name: "Boxing Punches", duration: "3 min", intensity: "High", equipment: ["bodyweight"] },
      { name: "Plank Shoulder Taps", sets: 3, reps: "20 total", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Kettlebell Clean and Press", sets: 3, reps: "10 per side", rest: "45 sec", equipment: ["kettlebells"] },
      { name: "TRX Rows", sets: 3, reps: "15", rest: "30 sec", equipment: ["trx"] },
      { name: "Dumbbell Thrusters", sets: 3, reps: "12", rest: "45 sec", equipment: ["dumbbells"] },
      { name: "Renegade Rows", sets: 3, reps: "10 per side", rest: "45 sec", equipment: ["dumbbells"] },
    ],
    "lower-body": [
      { name: "Jump Squats", sets: 4, reps: "15", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Box Jumps", sets: 3, reps: "12", rest: "45 sec", equipment: ["box"] },
      { name: "Lunge Jumps", sets: 3, reps: "10 per leg", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Speed Skaters", sets: 3, reps: "20 total", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Hill Sprints", sets: 5, duration: "30 sec", rest: "1 min", equipment: ["bodyweight"] },
      { name: "Kettlebell Swings", sets: 3, reps: "20", rest: "45 sec", equipment: ["kettlebells"] },
      { name: "Sled Push", sets: 3, distance: "20m", rest: "1 min", equipment: ["sled"] },
      { name: "Step-ups", sets: 3, reps: "15 per leg", rest: "45 sec", equipment: ["box", "bodyweight"] },
      { name: "Jumping Rope", duration: "3 min", intensity: "High", equipment: ["jump rope"] },
    ],
    push: [
      { name: "Push-up Variations", sets: 4, reps: "15", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Medicine Ball Chest Pass", sets: 3, reps: "15", rest: "30 sec", equipment: ["medicine ball"] },
      { name: "Dumbbell Punches", sets: 3, reps: "20 per arm", rest: "30 sec", equipment: ["dumbbells"] },
      { name: "Plyo Push-ups", sets: 3, reps: "10", rest: "45 sec", equipment: ["bodyweight"] },
      { name: "Kettlebell Press", sets: 3, reps: "12 per arm", rest: "30 sec", equipment: ["kettlebells"] },
      { name: "Burpees", sets: 3, reps: "12", rest: "45 sec", equipment: ["bodyweight"] },
    ],
    pull: [
      { name: "Battle Ropes", sets: 4, duration: "30 sec", rest: "30 sec", equipment: ["ropes"] },
      { name: "TRX Rows", sets: 3, reps: "15", rest: "30 sec", equipment: ["trx"] },
      { name: "Kettlebell High Pulls", sets: 3, reps: "12", rest: "30 sec", equipment: ["kettlebells"] },
      { name: "Renegade Rows", sets: 3, reps: "10 per side", rest: "45 sec", equipment: ["dumbbells"] },
      { name: "Medicine Ball Slams", sets: 3, reps: "15", rest: "30 sec", equipment: ["medicine ball"] },
      { name: "Band Pull-Aparts", sets: 3, reps: "20", rest: "30 sec", equipment: ["resistance bands"] },
    ],
    split: [
      { name: "Jumping Jacks", duration: "3 min", intensity: "Moderate", equipment: ["bodyweight"] },
      { name: "Mountain Climbers", sets: 3, reps: "20 per leg", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Kettlebell Swings", sets: 3, reps: "15", rest: "30 sec", equipment: ["kettlebells"] },
      { name: "Jump Squats", sets: 3, reps: "15", rest: "30 sec", equipment: ["bodyweight"] },
      { name: "Push-up to Row", sets: 3, reps: "10", rest: "45 sec", equipment: ["dumbbells"] },
      { name: "Burpees", sets: 3, reps: "10", rest: "45 sec", equipment: ["bodyweight"] },
    ],
  },
  flexibility: {
    "full-body": [
      { name: "Sun Salutation", sets: 3, duration: "2 min", equipment: ["bodyweight"] },
      {
        name: "World's Greatest Stretch",
        sets: 2,
        reps: "5 per side",
        duration: "30 sec hold",
        equipment: ["bodyweight"],
      },
      { name: "Downward Dog to Cobra", sets: 2, reps: "10", duration: "5 breaths each", equipment: ["bodyweight"] },
      { name: "Standing Forward Fold", duration: "1 min", equipment: ["bodyweight"] },
      { name: "Child's Pose to Cat-Cow", sets: 2, reps: "10", duration: "5 breaths each", equipment: ["bodyweight"] },
      { name: "Pigeon Pose", sets: 2, duration: "1 min per side", equipment: ["bodyweight"] },
      { name: "Butterfly Stretch", sets: 2, duration: "1 min", equipment: ["bodyweight"] },
      { name: "Spinal Twist", sets: 2, duration: "30 sec per side", equipment: ["bodyweight"] },
      { name: "Hip Flexor Stretch", sets: 2, duration: "45 sec per side", equipment: ["bodyweight"] },
      { name: "Foam Rolling Sequence", duration: "5 min", equipment: ["foam roller"] },
    ],
    "upper-body": [
      { name: "Thread the Needle", sets: 2, reps: "5 per side", duration: "30 sec hold", equipment: ["bodyweight"] },
      { name: "Chest Opener", sets: 2, duration: "45 sec hold", equipment: ["bodyweight"] },
      { name: "Shoulder Rolls", sets: 2, reps: "10 each direction", equipment: ["bodyweight"] },
      { name: "Eagle Arms", sets: 2, reps: "5 per side", duration: "30 sec hold", equipment: ["bodyweight"] },
      { name: "Wrist Stretches", sets: 2, duration: "30 sec each position", equipment: ["bodyweight"] },
      { name: "Neck Stretches", sets: 2, duration: "30 sec each direction", equipment: ["bodyweight"] },
      { name: "Lat Stretch with Band", sets: 2, duration: "45 sec per side", equipment: ["resistance bands"] },
      { name: "Tricep Stretch", sets: 2, duration: "30 sec per arm", equipment: ["bodyweight"] },
      { name: "Forearm Stretches", sets: 2, duration: "30 sec each", equipment: ["bodyweight"] },
    ],
    "lower-body": [
      { name: "Pigeon Pose", sets: 2, duration: "1 min per side", equipment: ["bodyweight"] },
      { name: "Lizard Pose", sets: 2, duration: "45 sec per side", equipment: ["bodyweight"] },
      { name: "Seated Forward Fold", sets: 2, duration: "1 min", equipment: ["bodyweight"] },
      { name: "Butterfly Stretch", sets: 2, duration: "1 min", equipment: ["bodyweight"] },
      { name: "Standing Quad Stretch", sets: 2, duration: "30 sec per leg", equipment: ["bodyweight"] },
      { name: "Hamstring Stretch with Band", sets: 2, duration: "45 sec per leg", equipment: ["resistance bands"] },
      { name: "Calf Stretch", sets: 2, duration: "30 sec per leg", equipment: ["bodyweight"] },
      { name: "Ankle Rotations", sets: 2, reps: "10 each direction", equipment: ["bodyweight"] },
      { name: "Frog Pose", sets: 2, duration: "45 sec", equipment: ["bodyweight"] },
      { name: "Foam Rolling Legs", duration: "5 min", equipment: ["foam roller"] },
    ],
    push: [
      { name: "Chest Opener", sets: 2, duration: "45 sec", equipment: ["bodyweight"] },
      { name: "Shoulder Stretch", sets: 2, duration: "30 sec per side", equipment: ["bodyweight"] },
      { name: "Tricep Stretch", sets: 2, duration: "30 sec per arm", equipment: ["bodyweight"] },
      { name: "Wall Angels", sets: 2, reps: "10", equipment: ["bodyweight"] },
      { name: "Child's Pose", sets: 2, duration: "1 min", equipment: ["bodyweight"] },
      { name: "Foam Rolling Chest and Shoulders", duration: "3 min", equipment: ["foam roller"] },
    ],
    pull: [
      { name: "Lat Stretch", sets: 2, duration: "45 sec per side", equipment: ["bodyweight"] },
      { name: "Cat-Cow", sets: 2, reps: "10", equipment: ["bodyweight"] },
      { name: "Thread the Needle", sets: 2, duration: "30 sec per side", equipment: ["bodyweight"] },
      { name: "Bicep Stretch", sets: 2, duration: "30 sec per arm", equipment: ["bodyweight"] },
      { name: "Foam Rolling Back", duration: "3 min", equipment: ["foam roller"] },
      { name: "Band Pull-Aparts", sets: 2, reps: "15", equipment: ["resistance bands"] },
    ],
    split: [
      { name: "World's Greatest Stretch", sets: 2, reps: "5 per side", equipment: ["bodyweight"] },
      { name: "Pigeon Pose", sets: 2, duration: "45 sec per side", equipment: ["bodyweight"] },
      { name: "Chest Opener", sets: 2, duration: "30 sec", equipment: ["bodyweight"] },
      { name: "Seated Forward Fold", sets: 2, duration: "45 sec", equipment: ["bodyweight"] },
      { name: "Spinal Twist", sets: 2, duration: "30 sec per side", equipment: ["bodyweight"] },
      { name: "Foam Rolling Full Body", duration: "5 min", equipment: ["foam roller"] },
    ],
  },
  hypertrophy: {
    "full-body": [
      {
        name: "Barbell Squat",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Bench Press",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Romanian Deadlift",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Lat Pulldown",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["machine", "cables"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Dumbbell Shoulder Press",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Leg Extensions",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      { name: "Bicep Curls", sets: 3, reps: "12-15", rest: "60 sec", equipment: ["dumbbells"], muscleGroup: "Arms" },
      { name: "Tricep Pushdowns", sets: 3, reps: "12-15", rest: "60 sec", equipment: ["cables"], muscleGroup: "Arms" },
      {
        name: "Calf Raises",
        sets: 4,
        reps: "15-20",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
    ],
    "upper-body": [
      {
        name: "Incline Bench Press",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Seated Cable Rows",
        sets: 4,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["cables"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Dumbbell Shoulder Press",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Lat Pulldown",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["machine", "cables"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Chest Flyes",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "cables"],
        muscleGroup: "Upper Body Push",
      },
      { name: "Face Pulls", sets: 3, reps: "15-20", rest: "60 sec", equipment: ["cables"], muscleGroup: "Shoulders" },
      {
        name: "Bicep Curls",
        sets: 4,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "barbells"],
        muscleGroup: "Arms",
      },
      {
        name: "Tricep Extensions",
        sets: 4,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "cables"],
        muscleGroup: "Arms",
      },
      {
        name: "Lateral Raises",
        sets: 3,
        reps: "15-20",
        rest: "60 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
    ],
    "lower-body": [
      {
        name: "Barbell Squat",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Romanian Deadlift",
        sets: 4,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Leg Press",
        sets: 3,
        reps: "12-15",
        rest: "90 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Leg Curls",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Leg Extensions",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Hip Thrusts",
        sets: 3,
        reps: "12-15",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Calf Raises",
        sets: 5,
        reps: "15-20",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Adductor Machine",
        sets: 3,
        reps: "15-20",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Abductor Machine",
        sets: 3,
        reps: "15-20",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
    ],
    push: [
      {
        name: "Bench Press",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Incline Dumbbell Press",
        sets: 4,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Shoulder Press",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Chest Flyes",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "cables"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Lateral Raises",
        sets: 3,
        reps: "15-20",
        rest: "60 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      { name: "Tricep Pushdowns", sets: 4, reps: "12-15", rest: "60 sec", equipment: ["cables"], muscleGroup: "Arms" },
      {
        name: "Overhead Tricep Extensions",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "cables"],
        muscleGroup: "Arms",
      },
      {
        name: "Dips",
        sets: 3,
        reps: "10-15",
        rest: "90 sec",
        equipment: ["bodyweight", "machine"],
        muscleGroup: "Upper Body Push",
      },
    ],
    pull: [
      {
        name: "Barbell Rows",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Lat Pulldown",
        sets: 4,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["machine", "cables"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Seated Cable Rows",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["cables"],
        muscleGroup: "Upper Body Pull",
      },
      { name: "Face Pulls", sets: 3, reps: "15-20", rest: "60 sec", equipment: ["cables"], muscleGroup: "Shoulders" },
      {
        name: "Shrugs",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "barbells"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Bicep Curls",
        sets: 4,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "barbells"],
        muscleGroup: "Arms",
      },
      { name: "Hammer Curls", sets: 3, reps: "12-15", rest: "60 sec", equipment: ["dumbbells"], muscleGroup: "Arms" },
      {
        name: "Preacher Curls",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["dumbbells", "barbells", "machine"],
        muscleGroup: "Arms",
      },
    ],
    split: [
      {
        name: "Bench Press",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Barbell Squat",
        sets: 4,
        reps: "8-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Lat Pulldown",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["machine", "cables"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Romanian Deadlift",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["barbells"],
        muscleGroup: "Lower Body Pull",
      },
      {
        name: "Shoulder Press",
        sets: 3,
        reps: "10-12",
        rest: "90 sec",
        equipment: ["barbells", "dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Leg Extensions",
        sets: 3,
        reps: "12-15",
        rest: "60 sec",
        equipment: ["machine"],
        muscleGroup: "Lower Body Push",
      },
      { name: "Bicep Curls", sets: 3, reps: "12-15", rest: "60 sec", equipment: ["dumbbells"], muscleGroup: "Arms" },
      { name: "Tricep Pushdowns", sets: 3, reps: "12-15", rest: "60 sec", equipment: ["cables"], muscleGroup: "Arms" },
    ],
  },
  endurance: {
    "full-body": [
      {
        name: "Circuit Training",
        sets: 3,
        reps: "15-20 per exercise",
        rest: "30 sec between exercises, 2 min between sets",
        equipment: ["bodyweight", "dumbbells"],
      },
      {
        name: "Bodyweight Squats",
        sets: 3,
        reps: "20-25",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Push-ups",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Inverted Rows",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight", "trx"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Walking Lunges",
        sets: 3,
        reps: "20 steps",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      { name: "Plank", sets: 3, duration: "45-60 sec", rest: "30 sec", equipment: ["bodyweight"], muscleGroup: "Core" },
      {
        name: "Mountain Climbers",
        sets: 3,
        reps: "30 sec",
        rest: "15 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Core",
      },
      { name: "Jumping Jacks", sets: 3, duration: "45 sec", rest: "15 sec", equipment: ["bodyweight"] },
    ],
    "upper-body": [
      {
        name: "Push-ups",
        sets: 4,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Inverted Rows",
        sets: 4,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight", "trx"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Dumbbell Shoulder Press",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Band Pull-Aparts",
        sets: 3,
        reps: "20-25",
        rest: "30 sec",
        equipment: ["resistance bands"],
        muscleGroup: "Upper Body Pull",
      },
      { name: "Tricep Dips", sets: 3, reps: "15-20", rest: "30 sec", equipment: ["bodyweight"], muscleGroup: "Arms" },
      { name: "Bicep Curls", sets: 3, reps: "15-20", rest: "30 sec", equipment: ["dumbbells"], muscleGroup: "Arms" },
      {
        name: "Lateral Raises",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
    ],
    "lower-body": [
      {
        name: "Bodyweight Squats",
        sets: 4,
        reps: "20-25",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Walking Lunges",
        sets: 4,
        reps: "20 steps",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Glute Bridges",
        sets: 3,
        reps: "20-25",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Step-ups",
        sets: 3,
        reps: "15-20 per leg",
        rest: "30 sec",
        equipment: ["bodyweight", "box"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Calf Raises",
        sets: 3,
        reps: "25-30",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Wall Sit",
        sets: 3,
        duration: "45-60 sec",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Banded Lateral Walks",
        sets: 3,
        reps: "15-20 steps each direction",
        rest: "30 sec",
        equipment: ["resistance bands"],
        muscleGroup: "Lower Body Push",
      },
    ],
    push: [
      {
        name: "Push-ups",
        sets: 4,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Dumbbell Bench Press",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Shoulder Press",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      { name: "Tricep Dips", sets: 3, reps: "15-20", rest: "30 sec", equipment: ["bodyweight"], muscleGroup: "Arms" },
      {
        name: "Lateral Raises",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      { name: "Tricep Pushdowns", sets: 3, reps: "15-20", rest: "30 sec", equipment: ["cables"], muscleGroup: "Arms" },
    ],
    pull: [
      {
        name: "Inverted Rows",
        sets: 4,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight", "trx"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Band Pull-Aparts",
        sets: 3,
        reps: "20-25",
        rest: "30 sec",
        equipment: ["resistance bands"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Dumbbell Rows",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Face Pulls",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["cables", "resistance bands"],
        muscleGroup: "Shoulders",
      },
      { name: "Bicep Curls", sets: 3, reps: "15-20", rest: "30 sec", equipment: ["dumbbells"], muscleGroup: "Arms" },
      {
        name: "Reverse Flyes",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Upper Body Pull",
      },
    ],
    split: [
      {
        name: "Push-ups",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Upper Body Push",
      },
      {
        name: "Bodyweight Squats",
        sets: 3,
        reps: "20-25",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Inverted Rows",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["bodyweight", "trx"],
        muscleGroup: "Upper Body Pull",
      },
      {
        name: "Walking Lunges",
        sets: 3,
        reps: "20 steps",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      {
        name: "Shoulder Press",
        sets: 3,
        reps: "15-20",
        rest: "30 sec",
        equipment: ["dumbbells"],
        muscleGroup: "Shoulders",
      },
      {
        name: "Glute Bridges",
        sets: 3,
        reps: "20-25",
        rest: "30 sec",
        equipment: ["bodyweight"],
        muscleGroup: "Lower Body Push",
      },
      { name: "Tricep Dips", sets: 3, reps: "15-20", rest: "30 sec", equipment: ["bodyweight"], muscleGroup: "Arms" },
      { name: "Bicep Curls", sets: 3, reps: "15-20", rest: "30 sec", equipment: ["dumbbells"], muscleGroup: "Arms" },
    ],
  },
}

